version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app --log-level debug
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  # Map the host's port 5432 to the container's port 5432
    env_file:
      - ./.env.prod.db
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume: